// ignore_for_file: must_be_immutable

part of 'checkuserlogined_cubit.dart';

class CheckuserloginedState {
  bool? isLoggined;
  String? firstName,
      name,
      lastName,
      stateName,
      dateOfBirth,
      anniversaryDate,
      gender,
      maritalStatus,
      occupation,
      countryCode,
      mobileNumber,
      email,
      username,
      photoUrl,
      userUid,
      role,
      country,
      facebook,
      twitter,
      linkedin,
      instagram,
      bio;
  int? noOfPublishedArticles;
  User? user;
  List<dynamic>? favCategories;
  CheckuserloginedState(
      {required this.isLoggined,
      this.email,
      this.name,
      this.firstName,
      this.lastName,
      this.anniversaryDate,
      this.country,
      this.photoUrl,
      this.countryCode,
      this.mobileNumber,
      this.facebook,
      this.instagram,
      this.linkedin,
      this.twitter,
      this.role,
      this.user,
      this.favCategories,
      this.username,
      this.userUid,
      this.dateOfBirth,
      this.gender,
      this.maritalStatus,
      this.occupation,
      this.stateName,
      this.bio,
      this.noOfPublishedArticles});

  CheckuserloginedState copyWith(
      {bool? checkLogin,
      String? nme,
      String? fName,
      String? lName,
      String? em,
      String? usernme,
      String? pUrl,
      String? rle,
      String? uUid,
      String? ctry,
      String? fb,
      String? twitterAcc,
      String? insta,
      String? linkedinAcc,
      String? mobileCode,
      String? phoneNummber,
      String? state,
      String? birtDate,
      String? annivDate,
      String? job,
      String? marital,
      String? personalInfo,
      String? userGender,
      List<dynamic>? favCat,
      User? usr,
      int? noOfArticles}) {
    return CheckuserloginedState(
        isLoggined: checkLogin,
        email: em,
        firstName: fName,
        lastName: lName,
        name: nme,
        countryCode: mobileCode,
        mobileNumber: phoneNummber,
        role: rle,
        country: ctry,
        favCategories: favCat,
        user: usr,
        photoUrl: pUrl,
        userUid: uUid,
        facebook: fb,
        instagram: insta,
        linkedin: linkedinAcc,
        username: usernme,
        twitter: twitterAcc,
        anniversaryDate: annivDate,
        dateOfBirth: birtDate,
        gender: userGender,
        maritalStatus: marital,
        occupation: job,
        stateName: state,
        bio: personalInfo,
        noOfPublishedArticles: noOfArticles);
  }
}
